import type { ThemeConfig } from './themeConfig';

export const defaultTheme: ThemeConfig = {
  body: '#1e1e1e',
  topBar: '#222',
  statusBar: '#181818',
  sidebar: '#e7e2df',
  sidebarText: '#333',
  settingsPanel: '#404040',
  settingsHeader: '#404040',
  settingsSection: '#2b2b2b',
  settingsInputBg: '#2b2b2b',
  settingsInputBorder: '#212121',
  settingsInputText: '#d9d9d9',
  text: '#d9d9d9',
  textSecondary: '#ccc',
  textTertiary: '#999',
  buttonBg: 'rgb(94, 94, 94)',
  buttonText: '#ebebeb',
  buttonHover: 'rgb(0, 115, 230)',
  buttonDisabled: '#ccc',
  infoBoxBg: '#333',
  infoBoxText: '#999',
  editorBreadcrumb: '#bbb',
  editorBreadcrumbHighlight: '#60a1d0',
  toolbarSearchBtnBg: '#444',
  toolbarInputBg: '#393939',
  toolbarInputBorder: '#444',
  toolbarInputText: '#ddd',
  toolbarMenuBg: '#222',
  toolbarMenuBorder: '#444',
  toolbarSectionTitle: '#888',
  toolbarSectionBorder: '#333',
  findInputBg: '#3c3c3c',
  findInputBorder: '#464647',
  findInputText: '#cccccc',
  filterToggleBg: 'rgba(0, 0, 0, .4)',
  filterToggleText: '#999',
  filterIconFilter: 'invert()',
  sidebarToggleBg: '#333',
  sidebarToggleBorder: '#1f1f1f',
  sidebarToggleIcon: '#888',
  settingsPaneBorder: '#212121',
  paneTopBarSelected: '#272729',
  paneTopBarUnselected: '#252526',
  
  // New color variables for index.tsx
  paneSplitControlsShadow: '#222',
  buttonDarkBg: '#333',
  buttonDarkBorder: '#111',
  buttonDarkText: '#fff',
  paneSplitBorder: '#555',
  paneSplitHover: '#555',
  tabCloseBg: '#333',
  tabCloseBorder: '#555',
  tabCloseText: '#cccccc',
  
  // Additional color variables for pane content
  emptyPaneBg: '#000005',
  emptyPaneText: '#131212ff',
  dropTargetBg: 'rgba(0, 0, 0, 0.95)',
  dropTargetText: '#bbb',
  
  // Tab colors
  tabDropTargetBg: '#105460',
  tabActiveBg: '#1e1e1e',
  tabHoverBg: '#303030',
  tabInactiveBg: '#292929',
  
  // Pane splitter colors
  paneSplitterBg: '#181818',
  paneSplitterHoverBg: '#105460',
  paneSplitterShadow: 'rgba(0,0,0,0.4)',
  
  // Sidebar resize handle colors
  sidebarResizeHandleBg: '#333',
  sidebarResizeHandleHoverBg: '#105460',
  
  // Top bar button colors
  topBarButtonBorder: '#1f1f1f',
  tabActiveText: '#e2e2e2',
  tabInactiveText: '#bbb',
  tabActiveBorder: '#007acc',
  tabInactiveBorder: 'grey',
  tabShadow: '#000',
  tabBorder: '#000',
  tabCloseHoverBg: '#555',
  
  // Tab content colors
  tabContentBg: '#1f1f1f',
  tabContentText: '#fff',
  
  // Menu and button colors
  menuHoverBg: '#efefef',
  menuHoverText: '#111',
  menuItemSelectedBg: '#094771',
  menuItemHoverBg: '#2a2d2e',
  menuItemText: '#cccccc',
  updateButtonBg: '#db0',
  updateButtonHoverBg: '#dd0',
  updateButtonActiveBg: '#ca0',
  updateButtonErrorBg: '#b93131',
  updateButtonErrorHoverBg: '#d84040',
  updateButtonErrorActiveBg: '#9f2a2a',
  browserBtnBg: '#333',
  browserBtnHoverBg: '#444',
  browserBtnShadow: '#000',
  
  // Workspace menu colors
  workspaceMenuText: '#ddd',
  workspaceMenuBg: '#000',
  workspaceMenuBorder: '#000',
  actionButtonText: '#222',
  actionButtonErrorText: '#fff',
  
  // Status bar colors
  statusBarBorder: '#111',
  statusBarItemDefaultColor: '#999',
  statusBarSuccessColor: '#51cf66',
  statusBarWarningColor: '#ffa500',
  statusBarErrorColor: '#ff6b6b',
  statusBarPendingColor: '#ffa500',
  statusBarDisconnectedColor: '#666',
  statusBarIndicatorBorder: '#666',
  statusBarIndicatorHighlight: '#fff',
  
  // Dialog colors
  dialogOverlayBg: 'rgba(0, 0, 0, 0.5)',
  dialogBg: '#2d2d2d',
  dialogBorder: '#454545',
  dialogText: '#cccccc',
  dialogTextSecondary: '#a3a3a3',
  dialogDangerText: '#f85149',
  dialogButtonCancelBg: 'transparent',
  dialogButtonCancelBorder: '#555',
  dialogButtonCancelText: '#cccccc',
  dialogButtonCancelHoverBg: '#555',
  dialogButtonConfirmBg: '#238636',
  dialogButtonConfirmBorder: '#2ea043',
  dialogButtonConfirmText: '#ffffff',
  dialogButtonConfirmHoverBg: '#1f6333',
  dialogButtonDangerBg: '#da3633',
  dialogButtonDangerBorder: '#f85149',
  dialogButtonDangerHoverBg: '#b91c1c',
  
  // File tree colors
  fileTreeIndicatorBg: '#256491ff',
  fileTreeIconColor: '#666',
  fileTreeButtonBg: 'rgba(0, 0, 0, 0.08)',
  fileTreeButtonHoverBg: 'rgba(59, 130, 246, 0.15)',
  fileTreeButtonBorder: 'rgba(0, 0, 0, 0.15)',
  fileTreeButtonHoverBorder: 'rgba(59, 130, 246, 0.4)',
  fileTreeButtonText: 'rgba(0, 0, 0, 0.5)',
  fileTreeButtonHoverText: 'rgba(59, 130, 246, 0.9)',
  fileTreeItemHoverBg: 'rgba(0, 0, 0, 0.1)',
  fileTreeItemSelectedBg: 'rgba(0, 150, 255, 0.3)',
  fileTreeItemCloseBg: 'rgba(0, 0, 0, 0.06)',
  fileTreeItemCloseHoverBg: 'rgba(59, 130, 246, 0.15)',
  fileTreeItemCloseBorder: 'rgba(0, 0, 0, 0.2)',
  fileTreeItemCloseText: 'rgba(0, 0, 0, 0.6)',
  fileTreeItemCloseHoverText: 'rgba(59, 130, 246, 0.9)',
  fileTreeFilterToggleBg: 'rgba(0, 0, 0, 0.08)',
  fileTreeFolderDropTargetBg: 'rgba(0, 150, 255, 0.2)',
  fileTreeDirtyIndicator: 'rgba(0, 0, 0, 0.8)',
  
  // Settings colors
  settingsBodyBg: '#404040',
  settingsStatusBoxBg: '#202020',
  settingsStatusDisconnectedColor: '#666',
  settingsButtonErrorBg: '#ff6b6b',
  settingsButtonSuccessBg: '#4ade80',
  settingsButtonSuccessText: '#1a1a1a',
  settingsButtonSecondaryBg: '#333',
  
  // Plugin marketplace colors
  marketplaceBodyBg: '#1e1e1e',
  marketplaceTabInactiveBg: 'transparent',
  marketplacePluginItemBg: '#2d2d2d',
  marketplacePluginItemActiveBg: '#0d2b0d',
  marketplacePluginItemActiveText: '#4ade80',
  marketplacePluginItemInactiveBg: '#2d2d2d',
  marketplacePluginItemInactiveText: '#ffa500',
  marketplaceTabActiveBorder: '#0073e6',
  
  // GitHub repo selector colors
  githubTextDefault: '#999',
  githubErrorBg: '#4a1a1a',
  githubErrorText: '#ff6b6b',
  githubItemBorder: '#2a2a2a',
  githubItemSelectedBg: '#1a4a6b',
  githubItemHoverBg: '#333',
  githubItemSelectedText: '#ffffff',
  githubItemDefaultText: '#d9d9d9',
  githubRepoBranchSelectedBg: '#0969da',
  githubRepoBranchDefaultBg: 'transparent',
  githubRepoBranchSelectedText: '#ffffff',
  githubRepoBranchHoverText: '#ffffff',
  githubRepoBranchHoverBg: '#4a6741',
  githubTagBg: '#4a4a4a',
  githubTagText: '#999',
  githubRepoOwnerText: '#666',
  githubRepoBranchDefaultText: '#d9d9d9'
};