import type { ThemeConfig } from './themeConfig';

export const lightTheme: ThemeConfig = {
  body: '#ffffff',
  topBar: '#f5f5f5',
  statusBar: '#e8e8e8',
  sidebar: '#f0f0f0',
  sidebarText: '#333',
  settingsPanel: '#ffffff',
  settingsHeader: '#ffffff',
  settingsSection: '#f5f5f5',
  settingsInputBg: '#ffffff',
  settingsInputBorder: '#d0d0d0',
  settingsInputText: '#333',
  text: '#333',
  textSecondary: '#666',
  textTertiary: '#666666',
  buttonBg: '#f0f0f0',
  buttonText: '#333',
  buttonHover: '#0073e6',
  buttonDisabled: '#ccc',
  infoBoxBg: '#f5f5f5',
  infoBoxText: '#666',
  editorBreadcrumb: '#666',
  editorBreadcrumbHighlight: '#0073e6',
  toolbarSearchBtnBg: '#f0f0f0',
  toolbarInputBg: '#ffffff',
  toolbarInputBorder: '#d0d0d0',
  toolbarInputText: '#333',
  toolbarMenuBg: '#ffffff',
  toolbarMenuBorder: '#d0d0d0',
  toolbarSectionTitle: '#666',
  toolbarSectionBorder: '#ddd',
  findInputBg: '#ffffff',
  findInputBorder: '#d0d0d0',
  findInputText: '#333',
  filterToggleBg: 'rgba(0, 0, 0, .1)',
  filterToggleText: '#666',
  filterIconFilter: 'invert(0)',
  sidebarToggleBg: '#f0f0f0',
  sidebarToggleBorder: '#d0d0d0',
  sidebarToggleIcon: '#666',
  settingsPaneBorder: '#d0d0d0',
  paneTopBarSelected: '#e8e8e8',
  paneTopBarUnselected: '#f0f0f0',
  
  // New color variables for index.tsx
  paneSplitControlsShadow: '#e0e0e0',
  buttonDarkBg: '#e0e0e0',
  buttonDarkBorder: '#b0b0b0',
  buttonDarkText: '#333',
  paneSplitBorder: '#c0c0c0',
  paneSplitHover: '#c0c0c0',
  tabCloseBg: '#e0e0e0',
  tabCloseBorder: '#c0c0c0',
  tabCloseText: '#666666',
  
  // Additional color variables for pane content
  emptyPaneBg: '#f5f5f5',
  emptyPaneText: '#e0e0e0',
  dropTargetBg: 'rgba(255, 255, 255, 0.95)',
  dropTargetText: '#666',
  
  // Tab colors
  tabDropTargetBg: '#4a90a4',
  tabActiveBg: '#ffffff',
  tabHoverBg: '#e8e8e8',
  tabInactiveBg: '#f0f0f0',
  
  // Pane splitter colors
  paneSplitterBg: '#e8e8e8',
  paneSplitterHoverBg: '#4a90a4',
  paneSplitterShadow: 'rgba(119, 117, 117, 0.2)',
  
  // Sidebar resize handle colors
  sidebarResizeHandleBg: '#d0d0d0',
  sidebarResizeHandleHoverBg: '#4a90a4',
  
  // Top bar button colors
  topBarButtonBorder: '#c0c0c0',
  tabActiveText: '#333',
  tabInactiveText: '#666',
  tabActiveBorder: '#0073e6',
  tabInactiveBorder: '#ccc',
  tabShadow: '#ccc',
  tabBorder: '#d0d0d0',
  tabCloseHoverBg: '#c0c0c0',
  
  // Tab content colors
  tabContentBg: '#ffffff',
  tabContentText: '#333',
  
  // Menu and button colors
  menuHoverBg: '#333',
  menuHoverText: '#efefef',
  menuItemSelectedBg: '#0969da',
  menuItemHoverBg: '#e8e8e8',
  menuItemText: '#333',
  updateButtonBg: '#db0',
  updateButtonHoverBg: '#dd0',
  updateButtonActiveBg: '#ca0',
  updateButtonErrorBg: '#b93131',
  updateButtonErrorHoverBg: '#d84040',
  updateButtonErrorActiveBg: '#9f2a2a',
  browserBtnBg: '#e0e0e0',
  browserBtnHoverBg: '#d0d0d0',
  browserBtnShadow: '#999',
  
  // Workspace menu colors
  workspaceMenuText: '#333',
  workspaceMenuBg: '#ffffff',
  workspaceMenuBorder: '#d0d0d0',
  actionButtonText: '#fff',
  actionButtonErrorText: '#fff',
  
  // File tree colors
  fileTreeIndicatorBg: '#256491ff',
  fileTreeIconColor: '#666',
  fileTreeButtonBg: 'rgba(0, 0, 0, 0.08)',
  fileTreeButtonHoverBg: 'rgba(59, 130, 246, 0.15)',
  fileTreeButtonBorder: 'rgba(0, 0, 0, 0.15)',
  fileTreeButtonHoverBorder: 'rgba(59, 130, 246, 0.4)',
  fileTreeButtonText: 'rgba(0, 0, 0, 0.5)',
  fileTreeButtonHoverText: 'rgba(59, 130, 246, 0.9)',
  fileTreeItemHoverBg: 'rgba(0, 0, 0, 0.1)',
  fileTreeItemSelectedBg: 'rgba(0, 150, 255, 0.3)',
  fileTreeItemCloseBg: 'rgba(0, 0, 0, 0.06)',
  fileTreeItemCloseHoverBg: 'rgba(59, 130, 246, 0.15)',
  fileTreeItemCloseBorder: 'rgba(0, 0, 0, 0.2)',
  fileTreeItemCloseText: 'rgba(0, 0, 0, 0.6)',
  fileTreeItemCloseHoverText: 'rgba(59, 130, 246, 0.9)',
  fileTreeFilterToggleBg: 'rgba(0, 0, 0, 0.08)',
  fileTreeFolderDropTargetBg: 'rgba(0, 150, 255, 0.2)',
  fileTreeDirtyIndicator: 'rgba(0, 0, 0, 0.8)',
  
  // Settings colors
  settingsBodyBg: '#ffffff',
  settingsStatusBoxBg: '#f5f5f5',
  settingsStatusDisconnectedColor: '#999',
  settingsButtonErrorBg: '#ff6b6b',
  settingsButtonSuccessBg: '#4ade80',
  settingsButtonSuccessText: '#1a1a1a',
  settingsButtonSecondaryBg: '#f0f0f0',
  
  // Plugin marketplace colors
  marketplaceBodyBg: '#ffffff',
  marketplaceTabInactiveBg: 'transparent',
  marketplacePluginItemBg: '#f5f5f5',
  marketplacePluginItemActiveBg: '#e8f5e8',
  marketplacePluginItemActiveText: '#2e7d32',
  marketplacePluginItemInactiveBg: '#fff8e1',
  marketplacePluginItemInactiveText: '#ed6c02',
  marketplaceTabActiveBorder: '#0073e6',
  
  // Status bar colors
  statusBarBorder: '#d0d0d0',
  statusBarItemDefaultColor: '#666',
  statusBarSuccessColor: '#2e7d32',
  statusBarWarningColor: '#ed6c02',
  statusBarErrorColor: '#d32f2f',
  statusBarPendingColor: '#ed6c02',
  statusBarDisconnectedColor: '#666666',
  statusBarIndicatorBorder: '#ccc',
  statusBarIndicatorHighlight: '#333',
  
  // Dialog colors
  dialogOverlayBg: 'rgba(0, 0, 0, 0.5)',
  dialogBg: '#ffffff',
  dialogBorder: '#d0d0d0',
  dialogText: '#333',
  dialogTextSecondary: '#666',
  dialogDangerText: '#d32f2f',
  dialogButtonCancelBg: 'transparent',
  dialogButtonCancelBorder: '#ccc',
  dialogButtonCancelText: '#333',
  dialogButtonCancelHoverBg: '#f0f0f0',
  dialogButtonConfirmBg: '#2e7d32',
  dialogButtonConfirmBorder: '#4caf50',
  dialogButtonConfirmText: '#ffffff',
  dialogButtonConfirmHoverBg: '#1b5e20',
  dialogButtonDangerBg: '#d32f2f',
  dialogButtonDangerBorder: '#f44336',
  dialogButtonDangerHoverBg: '#b71c1c',
  
  // GitHub repo selector colors
  githubTextDefault: '#666',
  githubErrorBg: '#f5e0e0',
  githubErrorText: '#d32f2f',
  githubItemBorder: '#d0d0d0',
  githubItemSelectedBg: '#0969da',
  githubItemHoverBg: '#e8e8e8',
  githubItemSelectedText: '#ffffff',
  githubItemDefaultText: '#333',
  githubRepoBranchSelectedBg: '#0969da',
  githubRepoBranchDefaultBg: 'transparent',
  githubRepoBranchSelectedText: '#ffffff',
  githubRepoBranchHoverText: '#ffffff',
  githubRepoBranchHoverBg: '#6b9cff',
  githubRepoBranchDefaultText: '#333',
  githubTagBg: '#e0e0e0',
  githubTagText: '#666',
  githubRepoOwnerText: '#666'
};